"""Write corpus/large/facts.yaml and manifest.yaml from the spec (deterministic).

Usage: uv run python -m scripts.corpus_v2.make_spec [--out corpus/large]
"""

import argparse
from collections import Counter
from pathlib import Path

import yaml

from scripts.corpus_v2.spec import SEED, build, to_dicts


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=Path, default=Path("corpus/large"))
    args = parser.parse_args()
    facts, docs = build()
    args.out.mkdir(parents=True, exist_ok=True)

    doc_ids = [d.doc_id for d in docs]
    dupes = [k for k, n in Counter(doc_ids).items() if n > 1]
    if dupes:
        raise SystemExit(f"duplicate doc ids: {dupes}")
    known = set(doc_ids)
    for d in docs:
        for m in d.mentions:
            if m["ref"] not in known and not any(x.startswith(m["ref"] + "-v") for x in known):
                raise SystemExit(f"{d.doc_id} mentions unknown doc {m['ref']}")
    fact_ids = {f.id for f in facts}
    for d in docs:
        for fid in d.facts:
            if fid not in fact_ids:
                raise SystemExit(f"{d.doc_id} lists unknown fact {fid}")

    (args.out / "facts.yaml").write_text(
        f"# Corpus v2 fact registry — generated by scripts/corpus_v2/make_spec.py (seed {SEED}).\n"
        "# Every number in corpus/large/docs comes from here; do not edit by hand.\n"
        + yaml.safe_dump(to_dicts(facts), allow_unicode=True, sort_keys=False, width=110),
        encoding="utf-8",
    )
    (args.out / "manifest.yaml").write_text(
        f"# Corpus v2 document manifest — generated by scripts/corpus_v2/make_spec.py (seed {SEED}).\n"  # noqa: E501
        + yaml.safe_dump(to_dicts(docs), allow_unicode=True, sort_keys=False, width=110),
        encoding="utf-8",
    )

    families = Counter(d.family for d in docs)
    labels = Counter(f.label for f in facts)
    words = sum((d.words[0] + d.words[1]) // 2 for d in docs)
    print(f"facts: {len(facts)} ({dict(labels)})")
    print(
        f"docs: {len(docs)} {dict(families)}; ~{words:,} words; "
        f"formats {dict(Counter(d.format for d in docs))}"
    )
    print(f"restricted docs: {sum(1 for d in docs if d.default_label != 'all' or d.restricted)}")
    print(f"versioned bases: {len({d.base for d in docs if d.superseded_by or d.supersedes})}")
    print(
        f"mentions: {sum(len(d.mentions) for d in docs)}; stale FAQs: "
        f"{sum(1 for d in docs if d.family == 'FAQ' and d.facts)}"
    )


if __name__ == "__main__":
    main()
